FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# halcyon

Halcyon is a self-care application for putting your mind and soul at ease
through daily journaling and spontaneous messages with others.


# Group Authorization

## Register [/auth/register]

### Register with credentials [POST]

+ Request (application/json)

    + Attributes (AuthRequest)

+ Response 200 (application/json)

    + Attributes (AuthResponse)

## Login [/auth/login]

### Login with credentials [POST]

+ Request (application/json)

    + Attributes (AuthRequest)

+ Response 200 (application/json)

    + Attributes (AuthResponse)

+ Response 401

        "Wrong password"

## Facebook [/auth/facebook]

### Login with facebook [GET]

+ Response 200 (application/json)

    + Attributes (AuthResponse)

+ Response 401

        "Failed to login to Facebook"
    

# Group Journal

## Journal Page [/journal/page{?limit}]

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `10`

### GET [GET]

+ Request (application/json)

    + Attributes (JournalPageRequest)

+ Response 200 (application/json)

    + Attributes (JournalPageResponse)
        
## Journal Block [/journal/block]

### POST [POST]

+ Request (application/json)

    + Attributes (JournalBlockRequest)

+ Response 200 (application/json)



# Group Conversation

# Group Soundfiles

# Group Blocked Users


# Data Structures

## AuthRequest (object)
- username: exampleUser123 (string)
- password: password123 (string)

## AuthResponse (User)
- token (Token)

## JournalPageRequest (object)
- token (Token)
- createdAt (string)

## JournalPageResponse (JournalPage)

## JournalBlockRequest (JournalBlock)
- token (Token)

## JournalBlock (object)
- prompt (string)
- content (string)
- mood (Mood)

## JournalPage (object)
- weather (string)
- location (string)
- createdAt (string)

## Mood (enum)
- HAPPY
- SAD
- ANGRY
- CONFUSED
- OK

## User (object)

- id: `13ed88c3-a7c3-4aef-a688-8705895cca47` (string)
- fbId: 1234567890873169 (string)
- name: john (string)
- alias: simple-cat (string)
- username: johnny (string)

## Token (string)
`aaAbbCciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA0MTMwODAxNjMsImV4cCI6MTYwMDQxMzE2NjU2M30.3zapZc7hXakM3xFZlkunOXH5BOYmMpZkGZVPtz-Sm8M`